name:                shax
version:             0.1.0.0
github:              "githubuser/shax"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/shax#readme>

dependencies:
- base >= 4.7 && < 5
- orthotope >= 0.1.6.0
- orthotope-hmatrix >= 0.1.2.0
- fin >= 0.3
- containers >= 0.6.7
- mtl >= 2.3.1
- recursion-schemes >= 5.2.2.5
- data-fix >= 0.3.2
- deriving-compat >= 0.6.5
- pretty >= 1.1.3.6
- lens >= 5.2.3
- QuickCheck >= 2.14.3
- generic-arbitrary >= 1.0.1
- transformers >= 0.6.1.1
#- mlir-hs

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fconstraint-solver-iterations=100
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src

executables:
  shax-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - shax

tests:
  shax-test:
    main:                Testing.hs
    source-dirs:         test
    dependencies:
    - shax
